### ISSUE TITLE
Hook does not prevent the user to press more than the required shortcuts

### ISSUE THREAD

**Issue by lucassr1994** [arthurtyukayev/use-keyboard-shortcut#30]
When I add something like

`const shortcutUndo = ['Control', 'Z'];
  useKeyboardShortcut(shortcutUndo, handleUndoShortcut);` 

and I press ctrl+shift+z or ctrl+y+z it still works.

Does anyone have an idea on how to prevent this?

**Comment by arthurtyukayev** [comment]
I've created a pull required #31, which should fix this issue.

Feel free to try it out.

**Comment by arthurtyukayev** [comment]
Closing due to new version.

**Comment by iamdhrooov** [comment]
This is still not resolved. If i define a shortcut like
```
useKeyboardShortcut(
          ['F'],
          () => screenfull.request(document.getElementById('media-player')),
          {
            overrideSystem: false,
            ignoreInputFields: true,
            repeatOnHold: false,
          }
        );
```

With this even if i press `cmd+f` or `anything+f`, it gets triggered which should not happen. How can i avoidd this?

**Comment by lucassr1994** [comment]
I did some changes that work, I'll open a pull request here later. @iamdhrooov you can try this: (sorry, the file I saved is not very well idented) 
`import { useEffect, useCallback, useReducer } from 'react';
const disabledEventPropagation = e => { if (e) if (e.stopPropagation) { e.stopPropagation(); } else if (window.event) { window.event.cancelBubble = true; } };
const blacklistedTargets = ['INPUT', 'TEXTAREA'];
const keysReducer = (state, action) => { switch (action.type) { case 'set-key-down': return { ...state, [action.key]: true }; case 'set-key-up': return { ...state, [action.key]: false }; case 'reset-keys': return { ...action.data }; default: return state; } };
const useShortcut = (shortcutKeys, callback, options) => {
    const { overrideSystem } = options || {};
    let unusedKeyFlag = [false]; const initalKeyMapping = shortcutKeys.reduce((currentKeys, key) => {
        currentKeys[key.toLowerCase()] = false; return currentKeys;
    }, {}); const [keys, setKeys] = useReducer(keysReducer, initalKeyMapping);
    const keydownListener = useCallback(assignedKey => keydownEvent => {
        if (!keydownEvent?.repeat) {
            if (keydownEvent?.key?.toLowerCase() === 'control')
                unusedKeyFlag = [false];
            if (!keys?.hasOwnProperty(keydownEvent?.key?.toLowerCase())) unusedKeyFlag.push(true);
            if (!unusedKeyFlag[unusedKeyFlag.length - 1]) {
                const loweredKey = assignedKey.toLowerCase();
                if (keydownEvent.repeat) return; if (blacklistedTargets.includes(keydownEvent.target.tagName)) return;
                if (loweredKey !== keydownEvent.key.toLowerCase()) return; if (keys[loweredKey] === undefined) return;
                if (overrideSystem) { keydownEvent.preventDefault(); disabledEventPropagation(keydownEvent); } setKeys({ type: 'set-key-down', key: loweredKey });
                return false;
            }
        }
    }, [keys, overrideSystem, unusedKeyFlag]);
    const keyupListener = useCallback(assignedKey => keyupEvent => {
        const raisedKey = assignedKey.toLowerCase();
        if (!keys?.hasOwnProperty(keyupEvent?.key?.toLowerCase())) unusedKeyFlag.pop(); if (blacklistedTargets.includes(keyupEvent.target.tagName)) return; if (keyupEvent?.key?.toLowerCase() !== raisedKey) return; if (keys[raisedKey] === undefined) return; if (overrideSystem) { keyupEvent.preventDefault(); disabledEventPropagation(keyupEvent); }
        setKeys({ type: 'set-key-up', key: raisedKey });
        return false;
    }, [keys, overrideSystem, unusedKeyFlag]);
    useEffect(() => {
        if (!Object.values(keys).filter(value => !value).length) {
            callback(keys); const newKeyMapping = initalKeyMapping;
            if (newKeyMapping?.hasOwnProperty('control')) newKeyMapping.control = true;
            if (newKeyMapping?.hasOwnProperty('shift')) newKeyMapping.shift = true;
            if (newKeyMapping?.hasOwnProperty('alt')) newKeyMapping.alt = true;
            if (newKeyMapping?.hasOwnProperty('arrowright')) newKeyMapping.arrowright = true;
            if (newKeyMapping?.hasOwnProperty('arrowleft')) newKeyMapping.arrowleft = true;
            setKeys({ type: 'reset-keys', data: initalKeyMapping });
        } else setKeys({ type: null });
    }, [callback, keys]);
    useEffect(() => {
        shortcutKeys.forEach(k => window.addEventListener('keydown', keydownListener(k))); return () => shortcutKeys.forEach(k => window.removeEventListener('keydown', keydownListener(k)));
    }, []);
    useEffect(() => {
        shortcutKeys.forEach(k => window.addEventListener('keyup', keyupListener(k))); return () => shortcutKeys.forEach(k => window.removeEventListener('keyup', keyupListener(k)));
    }, []);
};
export default useShortcut;`
